version: '3.8'

services:
  # ===== DEVELOPMENT APPLICATION =====
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: ai-resume-screener-dev
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - RELOAD=true
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-resume_screener_dev}
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/node_modules
      - dev_uploads:/app/uploads
      - dev_logs:/app/logs
    ports:
      - "${DEV_PORT:-8000}:8000"
      - "${DEBUG_PORT:-5678}:5678"  # Debug port
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]
    stdin_open: true
    tty: true

  # ===== DEVELOPMENT DATABASE =====
  db:
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-resume_screener_dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${DEV_POSTGRES_PORT:-5433}:5432"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
      - ./scripts/init-dev-db.sql:/docker-entrypoint-initdb.d/init-dev-db.sql:ro

  # ===== DEVELOPMENT REDIS =====
  redis:
    ports:
      - "${DEV_REDIS_PORT:-6380}:6379"
    volumes:
      - dev_redis_data:/data

  # ===== DEVELOPMENT TOOLS =====
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ai-resume-screener-mailhog
    ports:
      - "${MAILHOG_WEB_PORT:-8025}:8025"
      - "${MAILHOG_SMTP_PORT:-1025}:1025"
    networks:
      - app-network

  # ===== TESTING DATABASE =====
  test-db:
    image: postgres:14-alpine
    container_name: ai-resume-screener-test-db
    environment:
      POSTGRES_DB: test_resume_screener
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "${TEST_DB_PORT:-5434}:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - app-network

  # ===== DEVELOPMENT VOLUMES =====
volumes:
  dev_postgres_data:
    driver: local
  dev_redis_data:
    driver: local
  dev_uploads:
    driver: local
  dev_logs:
    driver: local
